import { z } from 'zod';
import { RaritySchema } from '../enums.js';
import {
  CardIdSchema,
  PackOpeningIdSchema,
  PackTemplateIdSchema,
  UserIdSchema,
} from '../primitives/id.js';

/**
 * One slot in a pack: an ordered position with a rarity-weight distribution.
 * This is how a real pack guarantees, say, exactly one rare with a small
 * chance of upgrading to something better.
 */
export const PackSlotSchema = z.object({
  weights: z.record(RaritySchema, z.number().nonnegative()),
});
export type PackSlot = z.infer<typeof PackSlotSchema>;

export const PackTemplateSchema = z.object({
  id: PackTemplateIdSchema,
  name: z.string().min(1),
  setFilter: z.record(z.string(), z.unknown()),
  cost: z.number().int().min(0),
  slotConfig: z.array(PackSlotSchema),
  active: z.boolean(),
});
export type PackTemplate = z.infer<typeof PackTemplateSchema>;

export const PackOpeningCardSchema = z.object({
  cardId: CardIdSchema,
  rarity: RaritySchema.nullable(),
});
export type PackOpeningCard = z.infer<typeof PackOpeningCardSchema>;

export const PackOpeningSchema = z.object({
  id: PackOpeningIdSchema,
  userId: UserIdSchema,
  templateId: PackTemplateIdSchema,
  openId: z.uuid(),
  cards: z.array(PackOpeningCardSchema),
  createdAt: z.coerce.date(),
});
export type PackOpening = z.infer<typeof PackOpeningSchema>;

/**
 * Body of `POST /packs/:templateId/open`.
 *
 * `openId` is the idempotency key, generated by the client. docs/API.md makes
 * this the guard against a double-click spending currency twice; the unique
 * constraint in PD-59 enforces it.
 */
export const OpenPackRequestSchema = z.object({
  openId: z.uuid(),
});
export type OpenPackRequest = z.infer<typeof OpenPackRequestSchema>;
